### ISSUE TITLE
Not getting logs with Prefix: "<SOOT_TUTORIAL>"

### ISSUE THREAD

**Issue by akshatgit** [noidsirius/SootTutorial#10]
Hi Navid,

I am running the Android logger tutorial. I was able to sign the apk and install it using adb, but when I run logcat with grep for "<SOOT_TUTORIAL>", I am not getting anything. However, I was able to get the calculator logs when I grep for 'numix'. 

Is this normal or am I missing anything?

Thanks,
Akshat

**Comment by noidsirius** [comment]
Hi Akshat,
Did you perform all steps in [chapter 3](https://github.com/noidsirius/SootTutorial#3-android-instrumentation)? You first have to instrument the app using `./gradlew run --args="AndroidLogger"` then sign and install it, and finally get the logs using `adb logcat | grep -e "<SOOT_TUTORIAL>"`. I tried it with Android emulators 27 and 30. If the problem is not fixed, could you please share your OS, emulator (or device) Android version?

**Comment by akshatgit** [comment]
It is working now! I might have missed the Gradle step. Thanks for the help!
